@startuml graph
'https://plantuml.com/class-diagram

abstract class AbstractFlyingObject {
    + int locationX
    + int locationY
    + int speedX
    + int speedY
    + forward(): void
    + vanish(): void
}

abstract class AbstractFlyingObject {
    # locationX:int
    # locationY:int
    # speedX:int
    # speedY:int
    # image:BufferedImage
    # width:int
    # height:int
    # isValid:boolean

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject flyingObject):boolean
    + setLocation(double locationX, double locationY):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}

abstract class AbstractAircraft {
    # int maxHp
    # int hp
    # BulletStrategy bulletStrategy:BulletStrategy

    + decreaseHp(int decrease): void
    + increaseHp(int increase): void
    + getHp(): int
    + abstract shoot(): List<BaseBullet>
}


class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    + {static} getHeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp):HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
}

class MobEnemy {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward(): void
    + shoot(): List<BaseBullet>
}

class EliteEnemy {
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward(): void
    + shoot(): List<BaseBullet>
}

class EliteProEnemy {
    + EliteProEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward(): void
    + shoot(): List<BaseBullet>
}

class ElitePlusEnemy{
    + ElitePlusEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward(): void
    + shoot(): List<BaseBullet>
}

class BossEnemy {
    + BossEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward(): void
    + shoot(): List<BaseBullet>
}



class BaseBullet{
    - power:int
    + BaseBullet(int locationX, int locationY, int speedX, int speedY, int power)
    + getPower():int
}

class HeroBullet {
    + HeroBullet(int locationX, int locationY, int speedX, int speedY, int power)
}

class EnemyBullet {
    + EnemyBullet(int locationX, int locationY, int speedX, int speedY, int power)
}

interface BulletStrategy {
    + abstract fire(AbstractAircraft aircraft):List<BaseBullet>
}

class NoBulletStrategy {
    + fire(AbstractAircraft aircraft):List<BaseBullet>
}
class SingleBulletStrategy {
    + fire(AbstractAircraft aircraft):List<BaseBullet>
}
class DoubleBulletStrategy {
    + fire(AbstractAircraft aircraft):List<BaseBullet>
}
class TripleBulletStrategy {
    + fire(AbstractAircraft aircraft):List<BaseBullet>
}

AbstractFlyingObject <|-- AbstractAircraft
AbstractFlyingObject <|-- BaseBullet

AbstractAircraft <|-- HeroAircraft
AbstractAircraft <|-- MobEnemy
AbstractAircraft <|-- EliteEnemy
AbstractAircraft <|-- EliteProEnemy
AbstractAircraft <|-- ElitePlusEnemy
AbstractAircraft <|-- BossEnemy

BulletStrategy <|.. NoBulletStrategy
BulletStrategy <|.. SingleBulletStrategy
BulletStrategy <|.. DoubleBulletStrategy
BulletStrategy <|.. TripleBulletStrategy
BulletStrategy <--o AbstractAircraft

BaseBullet <|-- HeroBullet
BaseBullet <|-- EnemyBullet

@enduml